name: Docker Test Build

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "crates/**"
      - "web/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Dockerfile"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CdsCTF
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ci:
              - 'Dockerfile'
              - '.github/workflows/test.yml'
            backend:
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'crates/**'
            frontend:
              - 'web/**'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all stages
        if: steps.changes.outputs.ci == 'true' || (steps.changes.outputs.backend == 'true' && steps.changes.outputs.frontend == 'true')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false

      - name: Build backend stage
        if: steps.changes.outputs.ci != 'true' && steps.changes.outputs.backend == 'true' && steps.changes.outputs.frontend != 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          target: backend

      - name: Build frontend stage
        if: steps.changes.outputs.ci != 'true' && steps.changes.outputs.frontend == 'true' && steps.changes.outputs.backend != 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          target: frontend
